core/urls.py
from django.urls import path
from .import views

app_name = 'core'

urlpatterns = [
    # path('register/', views.register, name='register'),
    # path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    #path("verification_mobile/", views.mobile_verification, name="verification_mobile"),
    #path("otp_verify/", views.otp_verification, name="otp_verify"),
 
    # ================================================================ Admin Dashboard urls ==========================================================
    path('admin/', views.admin, name='admin'),
    # =============================================================== SuperAdmin Dashboard urls ======================================================
    
    # Super-Admin Count URLs Here.
    path('superadmin_dashboard/', views.superadmin_dashboard, name='superadmin_dashboard'),
    path('superadmin_dashboard/superadmin_userRole/', views.superadmin_userRole, name='superadmin_userRole'),
    path('delete_admin_role/<int:role_id>/', views.delete_admin_role, name='delete_admin_role'),
    path('delete_scanner_role/<int:scanner_id>/', views.delete_scanner_role, name='delete_scanner_role'),
    path('superadmin_dashboard/totalregistercount/', views.superadmin_dashboard_totalregistercount, name='superadmin_dashboard_totalregistercount'),
    path('superadmin_dashboard/totalothercount/', views.superadmin_dashboard_totalothercount, name='superadmin_dashboard_totalothercount'),

    # Sub-Admin Count URLs Here.
    path('sub_admin_dashboard/', views.sub_admin_dashboard, name='sub_admin_dashboard'),
    path('subadmin_dashboard/subadmin_userRole/', views.subadmin_userRole, name='subadmin_userRole'),
    path('delete_subadmin_role/<int:role_id>/', views.delete_subadmin_role, name='delete_subadmin_role'),
    path('delete_subscanner_role/<int:scanner_id>/', views.delete_subscanner_role, name='delete_subscanner_role'),

    # ================================================== Start Super Admin Chart URLs Here. ======================================
    path("superadmin_dashboard/vibhag-chart-data/", views.vibhag_chart_data, name="vibhag-chart-data"),
    path("superadmin_dashboard/nagar-chart-data/", views.nagar_chart_data, name="nagar_chart_data"),
    # ================================================== End Super Admin Chart URLs Here. =========================================
]

ghosh_warg/urls.py
from django.urls import path
from . import views

# modules name register here.
app_name = 'ghosh_warg'

# Create your urls here.

urlpatterns = [ 
    path("", views.mobile_verification, name="mobile_verification"),
    path("otp/", views.otp_verification, name="otp_verification"),  
    path('ghoshwargregisteration/', views.GhoshWargRegisteration, name='ghoshwargregisteration'),
    path('ghoshwargviewregistration/', views.GhoshWargViewRegistration, name='ghoshwargviewregistration'),
    path('ghoshwargupdateregistration/', views.GhoshWargUpdateRegistration, name='ghoshwargupdateregistration'),
    path('user_logout/', views.user_logout, name='userlogout'),
]

samautkarsh/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .smsapis import get_chetra_prant_mappings, get_registration_mappings

# URL patterns for the project Module Configuration

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('register_samautkarsh.urls', namespace='register_samautkarsh')),
    path('updated_registration/', include('updated_registration.urls', namespace='updated_registration')),
    path('dashboard/', include('core.urls', namespace='core')),
    path('scanner/', include('scanner_admin.urls', namespace='scanner_admin')),
    path('ghoshwarg/', include('ghosh_warg.urls', namespace='ghosh_warg')),      # घोष वर्ग
    path('ABPP/', include('akhilbhartiye.urls', namespace='akhilbhartiye')),      # घोष वर्ग 
    path('get-registration-mappings/', get_registration_mappings, name='get_registration_mappings'),  # Get All Registration Mappings
    path('get-chetra-prant-mappings/', get_chetra_prant_mappings, name='get_chetra_prant_mappings'),  # Get Chetra Prant Mappings
    # path('akhil-bhartiye/', include('akhilbhartiye.urls', namespace='akhilbhartiye')),    # कार्यकर्ता विकास वर्ग – प्रथम (सामान्य)
    # path('sangh-shiksha-varg-vishesh/', include('sangh_shiksha_varg_vishesh.urls', namespace='sangh_shiksha_varg_vishesh')),    # संघ शिक्षा वर्ग (विशेष)
    # path('sangh-shiksha-varg-samanya/', include('sangh_shiksha_varg_samanya.urls', namespace='sangh_shiksha_varg_samanya')),    # संघ शिक्षा वर्ग (सामान्य)
    # path('karyakarta-vikas-varg-pratham-samanya/', include('karyakarta_vikas_varg_pratham_samanya.urls', namespace='karyakarta_vikas_varg_pratham_samanya')),    # कार्यकर्ता विकास वर्ग – प्रथम (सामान्य)
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from .models import *


# Create your forms here.

# User Registration Form
class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email address already registered.')
        return email
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username already taken.')
        return username
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 8:
            raise forms.ValidationError('Password must be at least 8 characters long.')
        return password1
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match.')
        return password2

    
    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
class MobileForm(forms.Form):
    mobile = forms.CharField(max_length=10, min_length=10, required=True)

class OTPForm(forms.Form):
    otp = forms.CharField(max_length=6, min_length=6, required=True)


class RoleManagementForm(forms.ModelForm):
    class Meta:
        model = Admin
        fields = ['name', 'mobile', 'role', 'role_level', 'role_sublevel']

    role = forms.ChoiceField(
        choices=[(role, role) for role in Admin.objects.values_list('role', flat=True).distinct()],
        required=True
    )
    role_level = forms.ChoiceField(
        choices=[(role_level, role_level) for role_level in Admin.objects.values_list('role_level', flat=True).distinct()],
        required=True
    )
    role_sublevel = forms.ChoiceField(
        choices=[(role_sublevel, role_sublevel) for role_sublevel in Admin.objects.values_list('role_sublevel', flat=True).distinct()],
        required=True
    )


class ScannedPersonForm(forms.ModelForm):
    class Meta:
        model = ScannedPerson
        fields = ['mobile','person_scanned']

   
        

ghosh_warg/views.py
from samautkarsh.smsapis import send_registration_sms, send_otp, get_registration_mappings
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib import messages
from django.conf import settings
from io import BytesIO
from PIL import Image
import qrcode, os
import base64
from register_samautkarsh.models import *
from register_samautkarsh.forms import *
from .models import *
from .forms import *


# Create your views here.

# Step 1: Check if mobile exists
def mobile_verification(request):
    message=''
    mobile=''
        
    if request.method == "POST":
        form = MobileForm(request.POST)
        if form.is_valid():
            mobile = form.cleaned_data["mobile"]
            user_exists = RegisterSamautkarshRegistration.objects.filter(phone_number=mobile).exists()
            scanner_exists = ScannerApprovals.objects.filter(phone_number=mobile,role='scanner').exists()
            try:
                user_exists1= BarcodeScan.objects.filter(phone_number=mobile)
                if user_exists1.status=='Approve' or user_exists1.status=='Reject':
                     request.session["status"] = user_exists1.status
            except:
                pass
            if user_exists:
                send_otp(mobile)
                request.session["mobile"] = mobile  # Store mobile in session
                return redirect("ghosh_warg:otp_verification")

            elif scanner_exists:
                send_otp(mobile)
                request.session["mobile"] = mobile 
                request.session['role']='scanner' # Store mobile in session
                return redirect("ghosh_warg:otp_verification")
            else:
                send_otp(mobile)
                request.session["mobile"] = mobile  # Store mobile in session
                return redirect("ghosh_warg:otp_verification")            
    else:
        form = MobileForm()
    return render(request, "mobile_verification.html", {"form": form})

# Step 2: OTP Verification
def otp_verification(request):
    mobile = request.session.get("mobile")
    message = ""
    
    if not mobile:
        return redirect("ghosh_warg:mobile_verification")

    form = OTPForm()

    if request.method == "POST":
        form = OTPForm(request.POST)

        if form.is_valid():
            otp = form.cleaned_data["otp"]
            otp_record = RegisterSamautkarshOtp.objects.filter(mobile=mobile, otp=otp).first()

            if otp_record:
                # Save new user only after OTP verification
                RegisterSamautkarshUser.objects.create(mobile=mobile)

                # ✅ Set source_app to track app for future redirection
                request.session['source_app'] = 'register_samautkarsh'

                admin = Admin.objects.filter(mobile=mobile).first()
                if admin:
                    request.session['role_level'] = str(admin.role_level)
                    request.session['role'] = admin.role
                    request.session['role_sublevel'] = admin.role_sublevel

                    if admin.role == 'SUPERADMIN':
                        return redirect('core:superadmin_dashboard')
                    elif admin.role == 'SUBADMIN':
                        return redirect('core:sub_admin_dashboard')

                elif request.session.get('role') == 'scanner':
                    return redirect('scan_qr')

                # Check if user is already registered
                
                elif RegisterSamautkarshRegistration.objects.filter(phone_number=mobile).exists():
                    return redirect("ghosh_warg:ghoshwargviewregistration")

                # If new user, redirect to registration page
                
                return redirect("ghosh_warg:ghoshwargregisteration")
            else:
                message = "Invalid OTP. Try again."
                messages.error(request, message)
                return redirect("ghosh_warg:otp_verification")

    return render(request, "otp_verification.html", {"form": form})

# Ghosh Varg Registration here.
def GhoshWargRegisteration(request):
    if not request.session.get('mobile'):
         return redirect('ghosh_warg:otp_verification') 
    mobile_number = request.session.get('mobile')

    # Fetch mappings from the function
    mappings = get_registration_mappings(request)  

    form1 = RegistrationForm()
    form = GhoshVargRegisterForm()
    try:
        # Check if the phone number already exists in the database
        record = RegisterSamautkarshRegistration.objects.get(phone_number=mobile_number)
    except RegisterSamautkarshRegistration.DoesNotExist:
        record = None

    if record:
        # If a record exists, redirect to the verification page
        return redirect('ghosh_warg:mobile_verification')
    else:
        # If no record exists, proceed with registration
        if request.method == 'POST':
            form1 = RegistrationForm(request.POST)
            form = GhoshVargRegisterForm(request.POST)
            form.instance.phone_number = mobile_number
            
            if form.is_valid():
                # Set the mobile number from the session in the form
                form.instance.phone_number = mobile_number
                  # Use `form.instance` instead of directly setting form fields
                registration = form.save(commit=True)
                registration1 = form1.save(commit=True)

                # Generate QR code with name and nagar
                name = registration.name
                phone=registration.phone_number
                nagar = registration.nagar
                dayitv=registration.dayitv
                ekai=registration.ekai

                state=''
                try:
                    picode = PincodeMaster.objects.filter(pincode=registration.pincode, nagar_hindi=nagar)

                    state = None
                    qr_data = f"Name: {name}, Phone Number: {phone},Nagar: {nagar},state: {state}, Dayitv: {dayitv}, ekai:{ekai}"    
                    qr_data = base64.b64encode(qr_data.encode()).decode()
                except PincodeMaster.DoesNotExist:
                        state=registration.state
                        if not state:
                            state=''
                        qr_data = f"Name: {name}, Phone Number: {phone},Nagar: {nagar}, State: {state}, Dayitv: {dayitv}, ekai:{ekai}"
                        qr_data = base64.b64encode(qr_data.encode()).decode()

                qr = qrcode.QRCode(version=1, box_size=10, border=5)
                qr.add_data(qr_data)
                qr.make(fit=True)
                qr_img = qr.make_image(fill='black', back_color='white').convert('RGBA')  # Ensure RGBA mode

                # Load the logo image
                logo_path = os.path.join(settings.BASE_DIR, 'register_samautkarsh/static/register_samautkarsh/assets/img', 'logo.jpg')

                if os.path.exists(logo_path):

                    logo = Image.open(logo_path).convert("RGBA")  # Convert logo to RGBA

                    # Resize logo to fit inside the QR code
                    qr_size = qr_img.size[0]  # QR code width
                    logo_size = qr_size // 8   # Logo should be 1/4th of the QR code size
                    logo = logo.resize((logo_size, logo_size), Image.LANCZOS)

                    # Ensure QR code supports transparency before pasting
                    qr_img = qr_img.convert("RGBA")

                    # Paste logo at the center
                    logo_x = (qr_img.size[0] - logo.size[0]) // 2
                    logo_y = (qr_img.size[1] - logo.size[1]) // 2
                    qr_img.paste(logo, (logo_x, logo_y), logo)  # Ensure mask is used

                else:
                    pass
                    # print("❌ Logo not found! Skipping logo placement.")

                # Save the QR code
                qr_buffer = BytesIO()
                qr_img.save(qr_buffer, format="PNG")
                qr_buffer.seek(0)

                # Define the path for saving the QR code
                qr_directory = os.path.join(settings.BASE_DIR, 'register_samautkarsh','static', 'QRCodes')
                os.makedirs(qr_directory, exist_ok=True)  # Ensure the directory exists

                qr_filename = os.path.join(qr_directory, f"{phone}.jpg")
                barcodescan = BarcodeScan(name=name, phone_number=phone, nagar=nagar,dayitv=dayitv, qrcode=qr_filename)
                barcodescan.save()


                # Save the QR code image to the file
                with open(qr_filename, 'wb') as f:
                    f.write(qr_buffer.read())
                
                # Send an SMS to the user after registration
                send_registration_sms(phone) # Sms message call from smsapis.py

                request.session.flush()   
                # After successful registration and QR code generation, redirect to verification
                return redirect('ghosh_warg')

            else:
                print(form.errors)
                # If form is invalid, re-render the form with error messages
                return render(request, 'ghoshwargregisteration.html', {'form': form, 'phone_number': mobile_number, 'mappings':mappings})
    # Render the registration form if the record does not exist or on first load
    return render(request, 'ghoshwargregisteration.html', {'form': form, 'phone_number': mobile_number, 'mappings':mappings})



# view Registration informations!
def GhoshWargViewRegistration(request):
    # Check if mobile number is in session (user is verified)
    if not request.session.get('mobile'):
        return redirect('ghosh_warg:otp_verification')
    
    mobile_number = request.session.get('mobile')
    try:
        # Try to get the registration record
        record = GhoshVargRegister.objects.get(phone_number=mobile_number)
        barcode_record = BarcodeScan.objects.get(phone_number=mobile_number)

ghosh_warg/templates/mobile_verification.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'register_samautkarsh/assets/img/Samutkarsh_logo.png' %}" type="image/x-icon" />
    <title>Samutarkash | Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caudex:ital,wght@0,400;0,700;1,400;1,700&family=Forum&family=Roboto+Slab:wght@100..900&family=Roboto:ital,wght@0,100..900;1,100..900&family=Yatra+One&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arya:wght@400;700&family=Caudex:ital,wght@0,400;0,700;1,400;1,700&family=Forum&family=Hind:wght@300;400;500;600;700&family=Laila:wght@300;400;500;600;700&family=Palanquin+Dark:wght@400;500;600;700&family=Roboto+Slab:wght@100..900&family=Roboto:ital,wght@0,100..900;1,100..900&family=Yatra+One&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
            overflow-x: hidden;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            padding: 20px 10px;
            /* background-image: url('/static/register_samautkarsh/assets/img/bg_img.jpg'); */
            background-repeat: no-repeat;
            background-size: cover;
            font-family: "Hind", serif;
            background: linear-gradient(to right, #D32F2F, #F57C00, #FFCA28);
        }

        .form-container {
            background: white;
            /* border: 2px solid #8B0000; */
            border-radius: 12px;
            /* box-shadow: 20px 20px 26px rgba(255, 255, 255, 0.5), -20px -20px 26px rgba(255, 255, 255, 0.5); */
            padding: 30px;
            max-width: 450px;
            width: 100%;
            margin: auto;
            transition: transform 0.3s ease-in-out;
        }

        .form-label {
            font-size: 16px;
            font-weight: 700;
            color: #333;
        }
        .required::after {
            content: " *";
            color: red;
        }

        .form-control {
            font-size: 10px;
        }
       
        .btn{
                font-size: 16px;
                font-weight: 700;
            }

        
        @media (max-width: 768px) {
            .row .col-md-4 {
                width: 100%;
                margin-bottom: 10px;
            }
        }
        
        .form-container .form-control {
            font-size: 14px;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }

        .form-container .form-control:focus {
            border-color: #ff9800;
            box-shadow: 0px 0px 5px rgba(255, 152, 0, 0.75);
        }


        #mobileSection .form-control,
        #mobileSection .btn{
        height: 38px;
        }


    </style>
</head>
<body>
    <div class="form-container">
        <div class="text-center mb-5">
            <!-- Logo Image Section -->
            <div class="text-center mb-3" style="display: flex; justify-content: center; align-items: center;">
                <img src="{% static '/register_samautkarsh/assets/img/Samutkarsh_logo.png' %}" alt="RSS Delhi Prant"
                   style="width: 150px; height: 150px; margin-right: 10px; border-radius: 50%; object-fit: cover;">
             </div>
    
            <!-- Main Image Section -->
            <!-- <img src="{% static 'register_samautkarsh/assets/img/updated_banner.jpeg' %}" alt="Registration Image"
                style="width: 100%; max-width: 800px; height: auto; display: block; margin: 0 auto; border-radius: 2%;"> -->
            <hr>
        </div>


        <form method="POST" class="container">
            {% csrf_token %}
            <!-- {{ form.as_p }} -->
            <div class="row mb-3 mt-4" id="mobileSection">
                
                <div  class="col-8 col-md-9 col-sm-9">
                    
                    <label for="id_mobile" class="form-label  position-relative">मोबाइल नंबर:</label>
                    <input type="text" name="mobile" class="form-control" pattern="^\d{10}$" maxlength="10"  minlength="10" required id="id_mobile" autofocus>
                    <small id="mobileError" class="text-danger position-absolute" style="display: none; font-size: 12px;">
                        Please enter a valid mobile number!
                    </small>
    
                </div>
                <div class="col-4 col-md-3 col-sm-3 d-flex align-items-end">
                    <button type="submit" class="btn btn-sm btn-outline-success w-100">Submit</button>
                </div> 
            </div>     
            {% if messages %}
                {% for message in messages %}
                    <div class="row justify-content-center">
                        <div class="mt-2 col-10 col-md-10 alert alert-danger text-center" role="alert">
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}
             {% endif %}
        </form>
    </div>
    

    <script>
        // Mobile Number Input Validation
        document.getElementById("id_mobile").addEventListener("input", function () {
            const mobileInput = this.value;
            const mobileError = document.getElementById("mobileError");

            // Allow only numbers
            this.value = mobileInput.replace(/\D/g, "");

            // Validate length
            if (this.value.length === 10) {
                mobileError.style.display = "none"; // Hide error message
            } else {
                mobileError.style.display = "block"; // Show error message
            }
        });
    </script>

    <script type="text/javascript">
        // Push the current state to the history stack
        history.pushState(null, null, window.location.href);

        // Listen for the popstate event, which is triggered by back/forward navigation
        window.addEventListener('popstate', function () {
            // Push the state again to prevent back navigation
            history.pushState(null, null, window.location.href);
        });
    </script>
</body>
</html>

ghosh_warg/templates/otp_verification.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'register_samautkarsh/assets/img/Samutkarsh_logo.png' %}" type="image/x-icon" />
    <title>Samutarkash | Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caudex:ital,wght@0,400;0,700;1,400;1,700&family=Forum&family=Roboto+Slab:wght@100..900&family=Roboto:ital,wght@0,100..900;1,100..900&family=Yatra+One&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arya:wght@400;700&family=Caudex:ital,wght@0,400;0,700;1,400;1,700&family=Forum&family=Hind:wght@300;400;500;600;700&family=Laila:wght@300;400;500;600;700&family=Palanquin+Dark:wght@400;500;600;700&family=Roboto+Slab:wght@100..900&family=Roboto:ital,wght@0,100..900;1,100..900&family=Yatra+One&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
            overflow-x: hidden;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            padding: 20px 10px;
            /* background-image: url('/static/register_samautkarsh/assets/img/bg_img.jpg'); */
            background-repeat: no-repeat;
            background-size: cover;
            font-family: "Hind", serif;
            background: linear-gradient(to right, #D32F2F, #F57C00, #FFCA28);
        }

        .form-container {
            background: white;
            /* border: 2px solid #8B0000; */
            border-radius: 12px;
            /* box-shadow: 20px 20px 26px rgba(255, 255, 255, 0.5), -20px -20px 26px rgba(255, 255, 255, 0.5); */
            padding: 30px;
            max-width: 450px;
            width: 100%;
            margin: auto;
            transition: transform 0.3s ease-in-out;
        }

        .form-label {
            font-size: 16px;
            font-weight: 700;
            color: #333;
        }
        .required::after {
            content: " *";
            color: red;
        }

        .form-control {
            font-size: 10px;
        }
       
        .btn{
                font-size: 16px;
                font-weight: 700;
            }

        
        @media (max-width: 768px) {
            .row .col-md-4 {
                width: 100%;
                margin-bottom: 10px;
            }
        }
        
        .form-container .form-control {
            font-size: 14px;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }

        .form-container .form-control:focus {
            border-color: #ff9800;
            box-shadow: 0px 0px 5px rgba(255, 152, 0, 0.75);
        }

        .form-container .error-message {
            color: red;
            font-size: 12px;
            margin-top: 5px;
            display: none;
        }

        .form-container .input-error {
            border: 1px solid red !important;
        }

        #otpVerificationSection .form-control,
        #otpVerificationSection .btn{
        height: 38px;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <div class="text-center mb-5">
             <!-- Logo Image Section -->
             <div class="text-center mb-3" style="display: flex; justify-content: center; align-items: center;">
                <img src="{% static '/register_samautkarsh/assets/img/Samutkarsh_logo.png' %}" alt="RSS Delhi Prant"
                   style="width: 150px; height: 150px; margin-right: 10px; border-radius: 50%; object-fit: cover;">
             </div>
    
            <!-- Main Image Section -->
            <!-- <img src="{% static 'register_samautkarsh/assets/img/updated_banner.jpeg' %}" alt="Registration Image"
                style="width: 100%; max-width: 800px; height: auto; display: block; margin: 0 auto; border-radius: 2%;"> -->
            <hr>
        </div>


        <form method="POST" class="container">
            {% csrf_token %}
            <div class="row mb-3 mt-4" id="otpVerificationSection">

                <div  class="col-8 col-md-9 col-sm-9">
                    <label for="id_otp" class="form-label">OTP:</label>
                    <input type="text" name="otp" class="form-control" maxlength="6" minlength="6" required id="id_otp" autofocus>
                </div>
                <div class="col-4 col-md-3 col-sm-3 d-flex align-items-end">
                    <button type="submit" class="btn btn-sm btn-outline-success w-100">Verify</button>
                </div>  
            </div>   
            {% if messages %}
                {% for message in messages %}
                    <div class="row justify-content-center">
                        <div class="mt-2 col-10 col-md-10 alert alert-danger text-center" role="alert">
                            {{ message }}
                        </div>
                    </div>
                        {% endfor %}
             {% endif %}     
        </form>
    </div>

    <script type="text/javascript">
        // Push the current state to the history stack
        history.pushState(null, null, window.location.href);

        // Listen for the popstate event, which is triggered by back/forward navigation
        window.addEventListener('popstate', function () {
            // Push the state again to prevent back navigation
            history.pushState(null, null, window.location.href);
        });
    </script>  

</body>
</html>

ghosh_warg/templates/verify_registration.html
<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" href="{% static 'register_samautkarsh/assets/img/Samutkarsh_logo.png' %}" type="image/x-icon" />
    <title>Registration Verification</title>
</head>
<body>
    {% if verification_success %}
        <h1>Registration Verified Successfully!</h1>
        <p><strong>Name:</strong> {{ name }}</p>
        <p><strong>Nagar:</strong> {{ nagar }}</p>
        <h2>Your QR Code:</h2>
        <img src="data:image/png;base64,{{ qr_code_base64 }}" alt="QR Code">
    {% else %}
        <h1>Verification Failed</h1>
    {% endif %}


<script type="text/javascript">
    // Push the current state to the history stack
    history.pushState(null, null, window.location.href);

    // Listen for the popstate event, which is triggered by back/forward navigation
    window.addEventListener('popstate', function () {
        // Push the state again to prevent back navigation
        history.pushState(null, null, window.location.href);
    });
</script></body>
</html>